# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

pipelines:
  branches:
    master:
      - step:
          name: Build Docker Image
          services:
          - docker
          image: amazon/aws-cli
          script:
            - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 182907940373.dkr.ecr.us-east-1.amazonaws.com
            - docker build -t $ECR_REPO_NAME .
            - docker tag $ECR_REPO_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:latest
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:latest
      - step:
          name: Deploy to production
          services:
            - docker
          script:
            - pipe: atlassian/aws-ecs-deploy:1.1.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                CLUSTER_NAME: $AWS_CLUSTER_NAME
                SERVICE_NAME: $AWS_SERVICE_NAME
                TASK_DEFINITION: $AWS_TASK_DEF