# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  branches:
    master:
      - step:
          name: Installing
          caches:
          - node
          script:
          - npm install
      - step:
          name: Build Docker Image
          services:
          - docker
          image: atlassian/pipelines-awscli
          script:
          - echo $(aws ecr get-login-password --region $AWS_DEFAULT_REGION) > docker_push.sh
          - sh docker_push.sh
      - step:
          name: Deploy to production
          services:
            - docker
          script:
            - pipe: atlassian/aws-ecs-deploy:1.1.2
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                CLUSTER_NAME: $AWS_CLUSTER_NAME
                SERVICE_NAME: $AWS_SERVICE_NAME
                TASK_DEFINITION: $AWS_TASK_DEF